"""add low_stock_threshold, audit_log, request_comment

Revision ID: 240fa864fe21
Revises: fb93f0c9c1d4
Create Date: 2026-06-22 13:27:00.123944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240fa864fe21'
down_revision = 'fb93f0c9c1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_index('idx_delivery_delivery_date')
        batch_op.drop_index('idx_delivery_is_delivered')
        batch_op.drop_index('idx_delivery_received_by')
        batch_op.drop_index('idx_delivery_request_id')
        batch_op.drop_index('idx_delivery_tool_id')

    with op.batch_alter_table('notification_read', schema=None) as batch_op:
        batch_op.drop_index('idx_notification_read_user_id')

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_index('idx_request_date_requested')
        batch_op.drop_index('idx_request_status')
        batch_op.drop_index('idx_request_user_id')

    with op.batch_alter_table('requested_tool', schema=None) as batch_op:
        batch_op.drop_index('idx_requested_tool_request_id')
        batch_op.drop_index('idx_requested_tool_status')
        batch_op.drop_index('idx_requested_tool_tool_id')

    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('low_stock_threshold', sa.Integer(), nullable=True))
        batch_op.drop_index('idx_tool_category_id')

    with op.batch_alter_table('tool_usage', schema=None) as batch_op:
        batch_op.drop_index('idx_tool_usage_tool_id')
        batch_op.drop_index('idx_tool_usage_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_usage', schema=None) as batch_op:
        batch_op.create_index('idx_tool_usage_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_tool_usage_tool_id', ['tool_id'], unique=False)

    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.create_index('idx_tool_category_id', ['category_id'], unique=False)
        batch_op.drop_column('low_stock_threshold')

    with op.batch_alter_table('requested_tool', schema=None) as batch_op:
        batch_op.create_index('idx_requested_tool_tool_id', ['tool_id'], unique=False)
        batch_op.create_index('idx_requested_tool_status', ['status'], unique=False)
        batch_op.create_index('idx_requested_tool_request_id', ['request_id'], unique=False)

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.create_index('idx_request_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_request_status', ['status'], unique=False)
        batch_op.create_index('idx_request_date_requested', ['date_requested'], unique=False)

    with op.batch_alter_table('notification_read', schema=None) as batch_op:
        batch_op.create_index('idx_notification_read_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.create_index('idx_delivery_tool_id', ['tool_id'], unique=False)
        batch_op.create_index('idx_delivery_request_id', ['request_id'], unique=False)
        batch_op.create_index('idx_delivery_received_by', ['received_by'], unique=False)
        batch_op.create_index('idx_delivery_is_delivered', ['is_delivered'], unique=False)
        batch_op.create_index('idx_delivery_delivery_date', ['delivery_date'], unique=False)

    # ### end Alembic commands ###
