"""add supervisor_action system_setting and supervisor user fields

Revision ID: 93ae5d597fb3
Revises: 240fa864fe21
Create Date: 2026-08-11 16:57:21.392159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ae5d597fb3'
down_revision = '240fa864fe21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supervisor_email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('is_supervisor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('supervised_facilities', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('supervised_facilities')
        batch_op.drop_column('is_supervisor')
        batch_op.drop_column('supervisor_email')

    # ### end Alembic commands ###
