"""Initial migration with delivery tracking

Revision ID: fb93f0c9c1d4
Revises: 
Create Date: 2026-04-26 15:00:58.729737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb93f0c9c1d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.alter_column('distributed_by',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.alter_column('distributed_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
